Repository RedHat-UX/red-hat-design-system, pull requests merged in 2022-08, with the labels that each got.

#259 feat(secondary-nav): add `<rh-secondary-nav>`
  .changeset/three-chicken-confess.md
  elements/rh-dialog/rh-dialog.ts
  elements/rh-secondary-nav/README.md
  elements/rh-secondary-nav/demo/dark-variant.html
  elements/rh-secondary-nav/demo/demo.css
  elements/rh-secondary-nav/demo/proxy.html
  elements/rh-secondary-nav/demo/rh-secondary-nav.html
  elements/rh-secondary-nav/demo/rh-secondary-nav.js
  elements/rh-secondary-nav/docs/index.md
  elements/rh-secondary-nav/rh-secondary-nav-dropdown.css
  elements/rh-secondary-nav/rh-secondary-nav-dropdown.ts
  elements/rh-secondary-nav/rh-secondary-nav-lightdom.css
  elements/rh-secondary-nav/rh-secondary-nav-menu-section.css
  elements/rh-secondary-nav/rh-secondary-nav-menu-section.ts
  elements/rh-secondary-nav/rh-secondary-nav-menu.css
  elements/rh-secondary-nav/rh-secondary-nav-menu.ts
  elements/rh-secondary-nav/rh-secondary-nav-overlay.css
  elements/rh-secondary-nav/rh-secondary-nav-overlay.ts
  elements/rh-secondary-nav/rh-secondary-nav.css
  elements/rh-secondary-nav/rh-secondary-nav.ts
  elements/rh-secondary-nav/test/fixtures.ts
  elements/rh-secondary-nav/test/rh-secondary-nav.e2e.ts
  elements/rh-secondary-nav/test/rh-secondary-nav.spec.ts
  lib/RHDSScreenSizeController.ts
  lib/ScreenSizeController.ts
  lib/functions.ts
  lib/tokens.ts
  package.json
  spandx.config.cjs
Labels: new component, accessibiilty

#465 feat(tooltip): add rh-tooltip
  .changeset/tricky-glasses-jam.md
  docs/_data/importMap.cjs
  elements/rh-stat/rh-stat.ts
  elements/rh-tooltip/README.md
  elements/rh-tooltip/demo/demo.css
  elements/rh-tooltip/demo/rh-tooltip.html
  elements/rh-tooltip/demo/rh-tooltip.js
  elements/rh-tooltip/docs/rh-tooltip.md
  elements/rh-tooltip/rh-tooltip.css
  elements/rh-tooltip/rh-tooltip.ts
  elements/rh-tooltip/test/rh-tooltip.spec.ts
  package-lock.json
  package.json
Labels: in progress, for dev

#479 docs(secondary-nav): add docs page
  docs/assets/navigation-secondary/accessibility-tab-order.png
  docs/assets/navigation-secondary/best-practice-1.png
  docs/assets/navigation-secondary/best-practice-2.png
  docs/assets/navigation-secondary/best-practice-3.png
  docs/assets/navigation-secondary/best-practice-4.png
  docs/assets/navigation-secondary/best-practice-5.png
  docs/assets/navigation-secondary/breakpoints-large.png
  docs/assets/navigation-secondary/breakpoints-small.png
  docs/assets/navigation-secondary/collapsing-tray.png
  docs/assets/navigation-secondary/current-page-indicator.png
  docs/assets/navigation-secondary/expandable-tray-2-columns.png
  docs/assets/navigation-secondary/expandable-tray-3-columns.png
  docs/assets/navigation-secondary/expandable-tray-4-columns.png
  docs/assets/navigation-secondary/expandable-tray-content-desktop.png
  docs/assets/navigation-secondary/expandable-tray-content-mobile.png
  docs/assets/navigation-secondary/expandable-tray-desktop.png
  docs/assets/navigation-secondary/expandable-tray-mobile.png
  docs/assets/navigation-secondary/interaction-state-active.png
  docs/assets/navigation-secondary/interaction-state-default.png
  docs/assets/navigation-secondary/interaction-state-focus.png
  docs/assets/navigation-secondary/interaction-state-hover.png
  docs/assets/navigation-secondary/layout-desktop.png
  docs/assets/navigation-secondary/layout-mobile.png
  docs/assets/navigation-secondary/left-to-right-languages.png
  docs/assets/navigation-secondary/navigating-between-trays.png
  docs/assets/navigation-secondary/navigation-content.png
  docs/assets/navigation-secondary/navigation-slots.png
  docs/assets/navigation-secondary/navigation-text-styles.png
  docs/assets/navigation-secondary/product-name-text-stacking-1-lines.png
  docs/assets/navigation-secondary/product-name-text-stacking-2-lines.png
  docs/assets/navigation-secondary/product-name-text-stacking-3-lines.png
  docs/assets/navigation-secondary/product-name-text-styling.png
  docs/assets/navigation-secondary/right-to-left-languages.png
  docs/assets/navigation-secondary/scrolling-with-primary-down.png
  docs/assets/navigation-secondary/scrolling-with-primary-up.png
  docs/assets/navigation-secondary/scrolling-with-tray-1.png
  docs/assets/navigation-secondary/scrolling-with-tray-2.png
  docs/assets/navigation-secondary/secondary-nav-example.png
  docs/assets/navigation-secondary/secondary-nav-usage.png
  docs/assets/navigation-secondary/spacing-extra-large.png
  docs/assets/navigation-secondary/spacing-large.png
  docs/assets/navigation-secondary/spacing-small.png
  docs/assets/navigation-secondary/theme-option-dark.png
  docs/assets/navigation-secondary/theme-option-light.png
  docs/assets/navigation-secondary/zones-intro.png
  docs/assets/navigation-secondary/zones-small-breakpoints.png
  docs/scss/_utility.scss
Labels: documentation

#500 chore: autoupdate tokens
  .github/workflows/test.yml
  .stylelintrc.yml
  package-lock.json
  package.json
Labels: for dev
