Repository RedHat-UX/red-hat-design-system, pull requests merged in 2022-09, with the labels that each got.

#509 fix (footer): add em based tokens example
  elements/rh-footer/RhFooter.ts
  elements/rh-footer/demo/proxy.html
  elements/rh-footer/rh-footer.css
Labels: for dev

#505 style: apply stylelint
  .changeset/six-scissors-grab.md
  .stylelintrc.yml
  docs/assets/base.css
  docs/components/demos.html
  elements/rh-alert/demo/demo.css
  elements/rh-alert/rh-alert.css
  elements/rh-blockquote/rh-blockquote.css
  elements/rh-cta/demo/analytics.js
  elements/rh-cta/demo/demo.css
  elements/rh-cta/rh-cta.css
  elements/rh-demo/rh-demo.css
  elements/rh-dialog/demo/demo.css
  elements/rh-dialog/rh-dialog.css
  elements/rh-footer/RhFooter.ts
  elements/rh-footer/demo/global-footer.css
  elements/rh-footer/demo/proxy.html
  elements/rh-footer/rh-footer-block.css
  elements/rh-footer/rh-footer-lightdom.css
  elements/rh-footer/rh-footer-links.css
  elements/rh-footer/rh-footer-responsive.css.ts
  elements/rh-footer/rh-footer-social-link.css
  elements/rh-footer/rh-footer.css
  elements/rh-secondary-nav/demo/demo.css
  elements/rh-secondary-nav/rh-secondary-nav-dropdown.css
  elements/rh-secondary-nav/rh-secondary-nav-lightdom.css
  elements/rh-secondary-nav/rh-secondary-nav-menu-section.css
  elements/rh-secondary-nav/rh-secondary-nav-menu.css
  elements/rh-secondary-nav/rh-secondary-nav-overlay.css
  elements/rh-secondary-nav/rh-secondary-nav.css
  elements/rh-stat/demo/demo.css
  elements/rh-stat/rh-stat.css
  elements/rh-tooltip/demo/demo.css
  elements/rh-tooltip/rh-tooltip.css
  package-lock.json
  package.json
  web-dev-server.config.js
Labels: for dev

#527 docs: change demo link on the footer page
  docs/components/footer.njk
Labels: documentation, for design

#520 Updated images on Footer page
  docs/assets/footer/footer-anatomy.png
  docs/assets/footer/footer-behavior-columns.png
  docs/assets/footer/footer-behavior-hebrew.png
  docs/assets/footer/footer-behavior-japanese.png
  docs/assets/footer/footer-behavior-less-columns.png
  docs/assets/footer/footer-behavior-links.png
  docs/assets/footer/footer-best-practice-1.png
  docs/assets/footer/footer-best-practice-2.png
  docs/assets/footer/footer-example-cp.png
  docs/assets/footer/footer-example-developer.png
  docs/assets/footer/footer-example-pc.png
  docs/assets/footer/footer-focus-order.png
  docs/assets/footer/footer-interaction-state-active.png
  docs/assets/footer/footer-interaction-state-default.png
  docs/assets/footer/footer-interaction-state-focus.png
  docs/assets/footer/footer-interaction-state-hover.png
  docs/assets/footer/footer-sample.png
  docs/assets/footer/footer-small-screens-1.png
  docs/assets/footer/footer-small-screens-2.png
  docs/assets/footer/footer-spacing-1.png
  docs/assets/footer/footer-spacing-2.png
  docs/assets/footer/footer-spacing-3.png
  docs/assets/footer/footer-style-layout.png
  docs/assets/footer/footer-style-main.png
  docs/assets/footer/footer-usage-global.png
Labels: documentation

#510 docs: ux dot release notes v1.9.1
  docs/release-notes.njk
Labels: documentation, for design

#535 docs(typography): update content on Typography page
  docs/foundations/typography.njk
Labels: documentation, for design

#545 fix(secondary-nav): logo text padding
  elements/rh-secondary-nav/demo/dark-variant.html
  elements/rh-secondary-nav/demo/demo.css
  elements/rh-secondary-nav/rh-secondary-nav-lightdom.css
  elements/rh-secondary-nav/rh-secondary-nav-overlay.css
Labels: bug
