Repository RedHat-UX/red-hat-design-system, pull requests merged in 2023-06, with the labels that each got.

#1015 docs: fix cta and alert shortcodes
  docs/_plugins/shortcodes.cjs
  docs/_plugins/shortcodes/alert.cjs
  docs/_plugins/shortcodes/cta.cjs
  docs/_plugins/shortcodes/demo.cjs
  docs/_plugins/shortcodes/example.cjs
  docs/_plugins/shortcodes/helpers.cjs
  docs/_plugins/shortcodes/playground.cjs
  docs/_plugins/shortcodes/renderInstallation.cjs
  docs/_plugins/shortcodes/repoStatus.cjs
  docs/_plugins/shortcodes/section.cjs
Labels: documentation

#1011 docs(navigation-secondary): correcting issues
  docs/_data/repoStatus.csv
  docs/_plugins/shortcodes/repoStatus.cjs
  elements/rh-navigation-secondary/docs/00-overview.md
  elements/rh-navigation-secondary/docs/10-style.md
  elements/rh-navigation-secondary/docs/20-guidelines.md
  elements/rh-navigation-secondary/docs/nav-secondary-16px-spacer.png
  elements/rh-navigation-secondary/docs/nav-secondary-32px-spacer.png
  elements/rh-navigation-secondary/docs/nav-secondary-8px-spacer.png
  elements/rh-navigation-secondary/docs/nav-secondary-best-practice-1.png
  elements/rh-navigation-secondary/docs/nav-secondary-guidelines-responsive-slot-2-hidden.png
  elements/rh-navigation-secondary/docs/nav-secondary-guidelines-responsive-slot-2-visible.png
  elements/rh-navigation-secondary/docs/nav-secondary-guidelines-scrolling-primary-nav.png
  elements/rh-navigation-secondary/docs/nav-secondary-space-breakpoints-small.png
  elements/rh-navigation-secondary/docs/nav-secondary-usage-vs-primary.png
  elements/rh-navigation-secondary/rh-navigation-secondary.ts
Labels: documentation

#1032 docs(navigation-secondary): palette light on sample component
  elements/rh-navigation-secondary/docs/00-overview.md
Labels: documentation

#1020 docs(accordion): updated docs
  .changeset/heavy-olives-search.md
  docs/scss/components/_example.scss
  elements/rh-accordion/docs/00-overview.md
  elements/rh-accordion/docs/10-style.md
  elements/rh-accordion/docs/20-guidelines.md
  elements/rh-accordion/docs/30-code.md
  elements/rh-accordion/docs/40-accessibility.md
  elements/rh-accordion/docs/accordion-active-theme-dark.png
  elements/rh-accordion/docs/accordion-active-theme-light.png
  elements/rh-accordion/docs/accordion-anatomy.png
  elements/rh-accordion/docs/accordion-behavior-1.svg
  elements/rh-accordion/docs/accordion-behavior-2.svg
  elements/rh-accordion/docs/accordion-behavior-3.svg
  elements/rh-accordion/docs/accordion-best-practice-1.png
  elements/rh-accordion/docs/accordion-best-practice-2.png
  elements/rh-accordion/docs/accordion-best-practice-3.png
  elements/rh-accordion/docs/accordion-bestpractice-1.svg
  elements/rh-accordion/docs/accordion-bestpractice-2.svg
  elements/rh-accordion/docs/accordion-breakpoints-large.png
  elements/rh-accordion/docs/accordion-breakpoints-small.png
  elements/rh-accordion/docs/accordion-configuration.png
  elements/rh-accordion/docs/accordion-expanding-multiple-panels.png
  elements/rh-accordion/docs/accordion-focus-order.png
  elements/rh-accordion/docs/accordion-focus-theme-dark.png
  elements/rh-accordion/docs/accordion-focus-theme-light.png
  elements/rh-accordion/docs/accordion-hover-theme-dark.png
  elements/rh-accordion/docs/accordion-hover-theme-light.png
  elements/rh-accordion/docs/accordion-keyboard-interactions.png
  elements/rh-accordion/docs/accordion-layout.png
  elements/rh-accordion/docs/accordion-long-title-text.png
  elements/rh-accordion/docs/accordion-nested-panels.png
  elements/rh-accordion/docs/accordion-panel-content.png
  elements/rh-accordion/docs/accordion-responsive-1.svg
  elements/rh-accordion/docs/accordion-responsive-2.svg
  elements/rh-accordion/docs/accordion-responsive-3.svg
  elements/rh-accordion/docs/accordion-sample-element.png
  elements/rh-accordion/docs/accordion-sizes-best-practices.png
  elements/rh-accordion/docs/accordion-sizes.png
  elements/rh-accordion/docs/accordion-space.png
  elements/rh-accordion/docs/accordion-spacing-1.svg
  elements/rh-accordion/docs/accordion-spacing-2.svg
  elements/rh-accordion/docs/accordion-stacked-panels.png
  elements/rh-accordion/docs/accordion-style-1.svg
  elements/rh-accordion/docs/accordion-theme-1.svg
  elements/rh-accordion/docs/accordion-theme-2.svg
  elements/rh-accordion/docs/accordion-theme-dark.png
  elements/rh-accordion/docs/accordion-theme-light.png
  elements/rh-accordion/docs/accordion-title-text.png
  elements/rh-accordion/docs/accordion-touch-targets.png
  elements/rh-accordion/docs/accordion-usage-1.svg
  elements/rh-accordion/docs/accordion-usage-2.svg
  elements/rh-accordion/docs/accordion-vs-disclosure.png
  elements/rh-accordion/rh-accordion.ts
Labels: documentation

#966 docs(badge): badge docs cleanup
  .changeset/red-melons-begin.md
  docs/_includes/accessibility/1.4.1-A.md
  elements/rh-badge/docs/00-overview.md
  elements/rh-badge/docs/10-code.md
  elements/rh-badge/docs/10-style.md
  elements/rh-badge/docs/20-guidelines.md
  elements/rh-badge/docs/30-code.md
  elements/rh-badge/docs/40-accessibility.md
  elements/rh-badge/docs/badge-anatomy.png
  elements/rh-badge/docs/badge-best-practice-1.png
  elements/rh-badge/docs/badge-best-practice-2.png
  elements/rh-badge/docs/badge-configuration.png
  elements/rh-badge/docs/badge-counter-number.png
  elements/rh-badge/docs/badge-filtering.png
  elements/rh-badge/docs/badge-sample-element.png
  elements/rh-badge/docs/badge-space-and-width.png
  elements/rh-badge/docs/badge-theme-light.png
  elements/rh-badge/rh-badge.ts
Labels: documentation

#993 docs(pagination): update docs
  docs/elements/elements.html
  docs/scss/_utility.scss
  elements/rh-pagination/docs/00-overview.md
  elements/rh-pagination/docs/10-code.md
  elements/rh-pagination/docs/10-style.md
  elements/rh-pagination/docs/20-guidelines.md
  elements/rh-pagination/docs/30-code.md
  elements/rh-pagination/docs/40-accessibility.md
  elements/rh-pagination/docs/pagination-a11y-focus-order.png
  elements/rh-pagination/docs/pagination-a11y-keyboard-interactions.png
  elements/rh-pagination/docs/pagination-a11y-touch-targets.png
  elements/rh-pagination/docs/pagination-active-page-theme-dark.png
  elements/rh-pagination/docs/pagination-active-page-theme-light.png
  elements/rh-pagination/docs/pagination-alignment-pif-below-a.png
  elements/rh-pagination/docs/pagination-alignment-pif-below-b.png
  elements/rh-pagination/docs/pagination-alignment-pif-right-a.png
  elements/rh-pagination/docs/pagination-alignment-pif-right-b.png
  elements/rh-pagination/docs/pagination-anatomy.png
  elements/rh-pagination/docs/pagination-behavior-disabled-buttons.png
  elements/rh-pagination/docs/pagination-behavior-low-page-count.png
  elements/rh-pagination/docs/pagination-behavior-pif.png
  elements/rh-pagination/docs/pagination-behavior-truncation.png
  elements/rh-pagination/docs/pagination-best-practice-1.png
  elements/rh-pagination/docs/pagination-best-practice-2.png
  elements/rh-pagination/docs/pagination-best-practice-3.png
  elements/rh-pagination/docs/pagination-best-practice-4.png
  elements/rh-pagination/docs/pagination-compact-size.png
  elements/rh-pagination/docs/pagination-configuration.png
  elements/rh-pagination/docs/pagination-interaction-state-active-theme-dark.png
  elements/rh-pagination/docs/pagination-interaction-state-active-theme-light.png
  elements/rh-pagination/docs/pagination-interaction-state-focus-theme-dark.png
  elements/rh-pagination/docs/pagination-interaction-state-focus-theme-light.png
  elements/rh-pagination/docs/pagination-interaction-state-hover-theme-dark.png
  elements/rh-pagination/docs/pagination-interaction-state-hover-theme-light.png
  elements/rh-pagination/docs/pagination-pif-orientation-a.png
  elements/rh-pagination/docs/pagination-pif-orientation-b.png
  elements/rh-pagination/docs/pagination-responsive-no-pif-desktop.png
  elements/rh-pagination/docs/pagination-responsive-no-pif-mobile-large.png
  elements/rh-pagination/docs/pagination-responsive-no-pif-mobile-small.png
  elements/rh-pagination/docs/pagination-responsive-no-pif-tablet.png
  elements/rh-pagination/docs/pagination-responsive-no-pif.png
  elements/rh-pagination/docs/pagination-responsive-pif-below-desktop.png
  elements/rh-pagination/docs/pagination-responsive-pif-below-mobile-large.png
  elements/rh-pagination/docs/pagination-responsive-pif-below-mobile-small.png
  elements/rh-pagination/docs/pagination-responsive-pif-below-tablet.png
  elements/rh-pagination/docs/pagination-responsive-pif-below.png
  elements/rh-pagination/docs/pagination-responsive-pif-right-desktop.png
  elements/rh-pagination/docs/pagination-responsive-pif-right-mobile-large.png
  elements/rh-pagination/docs/pagination-responsive-pif-right-mobile-small.png
  elements/rh-pagination/docs/pagination-responsive-pif-right-tablet.png
  elements/rh-pagination/docs/pagination-responsive-pif-right.png
  elements/rh-pagination/docs/pagination-sample.png
  elements/rh-pagination/docs/pagination-space.png
  elements/rh-pagination/docs/pagination-style-sizes.png
  elements/rh-pagination/docs/pagination-theme-dark.png
  elements/rh-pagination/docs/pagination-theme-light.png
  elements/rh-pagination/docs/pagination-usage-sizes.png
  elements/rh-pagination/rh-pagination.ts
Labels: documentation

#1007 docs(elements): update images and summaries
  .pfe.config.json
  docs/_data/comingSoonItems.yaml
  docs/_includes/component/header.njk
  docs/_includes/feedback.html
  docs/_plugins/rhds.cjs
  docs/_plugins/shortcodes/example.cjs
  docs/elements/index.md
  docs/scss/components/_example.scss
  elements/rh-accordion/docs/screenshot.png
  elements/rh-accordion/rh-accordion.ts
  elements/rh-alert/docs/screenshot.png
  elements/rh-audio-player/docs/screenshot.png
  elements/rh-avatar/docs/screenshot.png
  elements/rh-badge/docs/screenshot.png
  elements/rh-badge/rh-badge.ts
  elements/rh-blockquote/docs/screenshot.png
  elements/rh-blockquote/rh-blockquote.ts
  elements/rh-breadcrumb/docs/00-overview.md
  elements/rh-breadcrumb/docs/screenshot.png
  elements/rh-button/docs/screenshot.png
  elements/rh-button/rh-button.ts
  elements/rh-card/docs/screenshot.png
  elements/rh-card/rh-card.ts
  elements/rh-cta/docs/screenshot.png
  elements/rh-cta/rh-cta.ts
  elements/rh-dialog/docs/screenshot.png
  elements/rh-dialog/rh-dialog.ts
  elements/rh-footer/docs/screenshot.png
  elements/rh-footnote/docs/00-overview.md
  elements/rh-footnote/docs/screenshot.png
  elements/rh-jump-links/docs/screenshot.png
  elements/rh-navigation-secondary/docs/screenshot.png
  elements/rh-navigation-secondary/rh-navigation-secondary.ts
  elements/rh-navigation/docs/screenshot.png
  elements/rh-pagination/docs/screenshot.png
  elements/rh-pagination/rh-pagination.ts
  elements/rh-popover/docs/screenshot.png
  elements/rh-progress-steps/docs/screenshot.png
  elements/rh-spinner/docs/screenshot.png
  elements/rh-spinner/rh-spinner.ts
  elements/rh-stat/docs/screenshot.png
  elements/rh-stat/rh-stat.ts
  elements/rh-subnav/docs/screenshot.png
  elements/rh-subnav/rh-subnav.ts
  elements/rh-tabs/docs/screenshot.png
  elements/rh-tabs/rh-tabs.ts
  elements/rh-tag/docs/screenshot.png
  elements/rh-tag/rh-tag.ts
  elements/rh-tooltip/docs/screenshot.png
Labels: documentation

#1002 docs(avatar): update docs
  docs/_data/repoStatus.csv
  elements/rh-avatar/docs/00-overview.md
  elements/rh-avatar/docs/10-style.md
  elements/rh-avatar/docs/20-guidelines.md
  elements/rh-avatar/docs/30-code.md
  elements/rh-avatar/docs/40-accessibility.md
  elements/rh-avatar/docs/avatar-16px-spacer.png
  elements/rh-avatar/docs/avatar-anatomy.png
  elements/rh-avatar/docs/avatar-behavior-1.svg
  elements/rh-avatar/docs/avatar-behavior-2.svg
  elements/rh-avatar/docs/avatar-best-practice-1.png
  elements/rh-avatar/docs/avatar-best-practice-2.png
  elements/rh-avatar/docs/avatar-best-practice-3.png
  elements/rh-avatar/docs/avatar-bestpractice-1.svg
  elements/rh-avatar/docs/avatar-bestpractice-2.svg
  elements/rh-avatar/docs/avatar-bestpractice-3.svg
  elements/rh-avatar/docs/avatar-bestpractice-4.svg
  elements/rh-avatar/docs/avatar-breakpoints-large.png
  elements/rh-avatar/docs/avatar-breakpoints-small.png
  elements/rh-avatar/docs/avatar-configuration.png
  elements/rh-avatar/docs/avatar-interaction-state-active-theme-dark.png
  elements/rh-avatar/docs/avatar-interaction-state-active-theme-light.png
  elements/rh-avatar/docs/avatar-interaction-state-focus-theme-dark.png
  elements/rh-avatar/docs/avatar-interaction-state-focus-theme-light.png
  elements/rh-avatar/docs/avatar-interaction-state-hover-theme-dark.png
  elements/rh-avatar/docs/avatar-interaction-state-hover-theme-light.png
  elements/rh-avatar/docs/avatar-job-details-text.png
  elements/rh-avatar/docs/avatar-line-breaks.png
  elements/rh-avatar/docs/avatar-links.png
  elements/rh-avatar/docs/avatar-plain.png
  elements/rh-avatar/docs/avatar-sample-1.svg
  elements/rh-avatar/docs/avatar-sample.png
  elements/rh-avatar/docs/avatar-space.png
  elements/rh-avatar/docs/avatar-spacing-1.svg
  elements/rh-avatar/docs/avatar-spacing-2.svg
  elements/rh-avatar/docs/avatar-style-1.svg
  elements/rh-avatar/docs/avatar-theme-1.svg
  elements/rh-avatar/docs/avatar-theme-2.svg
  elements/rh-avatar/docs/avatar-theme-3.svg
  elements/rh-avatar/docs/avatar-theme-4.svg
  elements/rh-avatar/docs/avatar-theme-dark.png
  elements/rh-avatar/docs/avatar-theme-light.png
  elements/rh-avatar/docs/avatar-usage-1.svg
  elements/rh-avatar/docs/avatar-usage-2.svg
  elements/rh-avatar/docs/avatar-usage-3.svg
  elements/rh-avatar/docs/avatar-usage-alignment.png
  elements/rh-avatar/docs/avatar-usage-sizes.png
  elements/rh-avatar/docs/avatar-usage-stacking.png
  elements/rh-avatar/docs/avatar-variations.png
  elements/rh-avatar/docs/avatar-writing-content.png
  elements/rh-avatar/rh-avatar.ts
Labels: documentation

#1042 fix(tabs): vertical tabs display as horizontal on small screens
  .changeset/khaki-snakes-fry.md
  elements/rh-tabs/rh-tab-panel.css
  elements/rh-tabs/rh-tab.css
  elements/rh-tabs/rh-tabs.css
Labels: bug

#1041 fix(subnav): correct default background color
  .changeset/twenty-panthers-report.md
  docs/scss/_layout.scss
  docs/scss/components/_site-navigation.scss
  docs/scss/components/_table-of-contents.scss
  elements/rh-subnav/demo/color-context.html
  elements/rh-subnav/demo/examples.html
  elements/rh-subnav/demo/rh-subnav.html
  elements/rh-subnav/docs/00-overview.md
  elements/rh-subnav/docs/10-code.md
  elements/rh-subnav/rh-subnav-lightdom.css
  elements/rh-subnav/rh-subnav.css
  elements/rh-subnav/rh-subnav.ts
Labels: bug, documentation

#1053 fix(accordion): roving tabindex for nested accordions
  .changeset/shiny-badgers-destroy.md
  package-lock.json
  package.json
Labels: bug

#1017 docs: format changelog
  .changeset/remove-husky-lintstaged.md
  .changeset/rh-tooltip-deprecate-bem-props.md
Labels: documentation

#1068 docs(footer): split out all subcomponents on code tab
  elements/rh-footer/docs/30-code.md
Labels: documentation

#1108 refactor(navigation secondary): improve context-provider use
  .changeset/spotty-pots-taste.md
  elements/rh-navigation-secondary/rh-navigation-secondary-dropdown.css
  elements/rh-navigation-secondary/rh-navigation-secondary-dropdown.ts
  elements/rh-navigation-secondary/rh-navigation-secondary-lightdom.css
  elements/rh-navigation-secondary/rh-navigation-secondary-menu.css
  elements/rh-navigation-secondary/rh-navigation-secondary-menu.ts
  elements/rh-navigation-secondary/rh-navigation-secondary.css
  elements/rh-navigation-secondary/rh-navigation-secondary.ts
Labels: enhancement
