Repository RedHat-UX/red-hat-design-system, pull requests merged in 2023-09, with the labels that each got.

#1212 fix(navigation-secondary): nav bar height
  .changeset/sweet-spoons-melt.md
  elements/rh-navigation-secondary/demo/long-logo-text.html
  elements/rh-navigation-secondary/rh-navigation-secondary-lightdom.css
  elements/rh-navigation-secondary/rh-navigation-secondary.css
Labels: bug

#1221 docs: update images for sticky-card and disclosure
  docs/patterns/disclosure/disclosure-responsive-3.png
  docs/patterns/disclosure/index.md
  docs/patterns/sticky-card/index.md
  docs/patterns/sticky-card/sticky-card-content.png
  docs/patterns/sticky-card/sticky-card-style.png
Labels: documentation

#1226 docs: don't render repo status table
  docs/_plugins/shortcodes/repoStatus.cjs
Labels: docs
