Repository RedHat-UX/red-hat-design-system, pull requests merged in 2023-08, with the labels that each got.

#1165 docs: correct header layout
  docs/elements/elements.html
  docs/scss/components/_header.scss
  docs/scss/styles.scss
Labels: bug, documentation, for dev

#1196 fix(tabs): vertical tabs text alignment
  .changeset/little-mice-work.md
  elements/rh-tabs/rh-tab.css
Labels: bug

#1202 docs: fix tokens icon samp element size
  docs/assets/tokens/tokens.css
Labels: documentation
