Repository RedHat-UX/red-hat-design-system, pull requests merged in 2023-11, with the labels that each got.

#1333 fix(navigation-secondary): initialization state of current page indicator
  .changeset/wet-flowers-double.md
  elements/rh-navigation-secondary/rh-navigation-secondary-dropdown.ts
Labels: bug

#1339 fix(navigation-secondary): add current page indicator to logo
  .changeset/six-dancers-repair.md
  elements/rh-navigation-secondary/demo/analytics.html
  elements/rh-navigation-secondary/demo/current-page-indicator.html
  elements/rh-navigation-secondary/demo/dark-variant.html
  elements/rh-navigation-secondary/demo/deprecated.html
  elements/rh-navigation-secondary/demo/long-logo-text.html
  elements/rh-navigation-secondary/demo/proxy.html
  elements/rh-navigation-secondary/demo/rh-navigation-secondary.html
  elements/rh-navigation-secondary/demo/translation.html
  elements/rh-navigation-secondary/rh-navigation-secondary-dropdown.css
  elements/rh-navigation-secondary/rh-navigation-secondary-lightdom.css
  elements/rh-navigation-secondary/rh-navigation-secondary.css
Labels: bug

#1341 docs: split Color page best practices into dos and dont's
  .changeset/color-page-update.md
  docs/assets/best-practices-danger-icon-red-orange.svg
  docs/assets/best-practices-success-icon.svg
  docs/assets/color/best-practices-custom-themes-correct.svg
  docs/assets/color/best-practices-custom-themes-wrong.svg
  docs/assets/color/best-practices-sufficient-contrast-correct.svg
  docs/assets/color/best-practices-sufficient-contrast-wrong.svg
  docs/foundations/color/accessibility.md
  docs/foundations/color/index.md
  docs/foundations/color/usage.md
  docs/scss/components/_best-practices.scss
  docs/scss/components/_example.scss
  docs/scss/styles.scss
Labels: docs

#1287 docs(table): markup guidance
  elements/rh-table/docs/30-code.md
  elements/rh-table/docs/40-accessibility.md
Labels: for a11y review

#1345 fix(tabs): move panel padding to host
  .changeset/funny-brooms-sell.md
  elements/rh-tabs/rh-tab-panel.css
Labels: feature

#1362 fix(tabs): tab button font-size default value
  .changeset/green-teachers-add.md
  elements/rh-tabs/rh-tabs.css
Labels: bug

#1347 docs(tabs): deprecate theme attribute
  .changeset/sour-owls-deny.md
  elements/rh-tabs/demo/deprecation.html
  elements/rh-tabs/rh-tabs.ts
Labels: docs
