Repository RedHat-UX/red-hat-design-system, pull requests merged in 2023-01, with the labels that each got.

#674 fix(docs): remove spinner demo page from ux.redhat.com
  .changeset/dry-pans-mix.md
  docs/components/spinner.njk
  elements/rh-secondary-nav/test/fixtures.js
  elements/rh-tag/rh-tag.css
  elements/rh-tag/rh-tag.ts
  elements/rh-tag/test/rh-tag.spec.ts
  package-lock.json
Labels: bug, documentation

#696 docs(secondary-nav): update pfe-icons in demos
  elements/rh-secondary-nav/demo/analytics.html
  elements/rh-secondary-nav/demo/dark-variant.html
  elements/rh-secondary-nav/demo/proxy.html
  elements/rh-secondary-nav/demo/rh-secondary-nav.html
  elements/rh-secondary-nav/demo/translation.html
Labels: documentation

#699 Updated Footer page with new language and images
  docs/assets/footer/footer-anatomy.png
  docs/assets/footer/footer-behavior-columns.png
  docs/assets/footer/footer-behavior-hebrew.png
  docs/assets/footer/footer-behavior-japanese.png
  docs/assets/footer/footer-behavior-less-columns.png
  docs/assets/footer/footer-behavior-links.png
  docs/assets/footer/footer-best-practice-1.png
  docs/assets/footer/footer-best-practice-2.png
  docs/assets/footer/footer-best-practice-3.png
  docs/assets/footer/footer-best-practice-4.png
  docs/assets/footer/footer-example-cp.png
  docs/assets/footer/footer-example-developer.png
  docs/assets/footer/footer-example-pc.png
  docs/assets/footer/footer-focus-order.png
  docs/assets/footer/footer-interaction-state-active.png
  docs/assets/footer/footer-interaction-state-default.png
  docs/assets/footer/footer-interaction-state-focus.png
  docs/assets/footer/footer-interaction-state-hover.png
  docs/assets/footer/footer-sample.png
  docs/assets/footer/footer-small-screens-1.png
  docs/assets/footer/footer-small-screens-2.png
  docs/assets/footer/footer-spacing-1.png
  docs/assets/footer/footer-spacing-2.png
  docs/assets/footer/footer-spacing-3.png
  docs/assets/footer/footer-style-layout.png
  docs/assets/footer/footer-style-main.png
  docs/assets/footer/footer-usage-global.png
  docs/assets/footer/footer-usage-universal.png
  docs/components/footer.njk
  package-lock.json
Labels: documentation

#594 feat(accordion): add rh-accordion
  .changeset/rare-camels-turn.md
  docs/components/accordion.njk
  docs/components/disclosure.njk
  docs/main.css
  elements/rh-accordion/README.md
  elements/rh-accordion/demo/color-context.html
  elements/rh-accordion/demo/color-context.js
  elements/rh-accordion/demo/demo.css
  elements/rh-accordion/demo/rh-accordion.html
  elements/rh-accordion/demo/rh-accordion.js
  elements/rh-accordion/demo/right-to-left.html
  elements/rh-accordion/docs/rh-accordion.md
  elements/rh-accordion/rh-accordion-header.css
  elements/rh-accordion/rh-accordion-header.ts
  elements/rh-accordion/rh-accordion-panel.css
  elements/rh-accordion/rh-accordion-panel.ts
  elements/rh-accordion/rh-accordion.css
  elements/rh-accordion/rh-accordion.ts
  elements/rh-accordion/test/rh-accordion.e2e.ts
  elements/rh-accordion/test/rh-accordion.spec.ts
  elements/rh-demo/rh-demo.css
  elements/rh-demo/rh-demo.ts
  elements/rh-footer/README.md
  elements/rh-footer/RhFooter.ts
  elements/rh-footer/rh-footer.css
  elements/rh-footer/test/rh-footer.spec.ts
  elements/rh-secondary-nav/README.md
  lib/context/color.ts
  package-lock.json
  package.json
Labels: new component, a11y review
