Repository RedHat-UX/red-hat-design-system, pull requests merged in 2023-03, with the labels that each got.

#718 feat(subnav): add `<rh-subnav>`
  .changeset/mean-teachers-smile.md
  elements/rh-subnav/README.md
  elements/rh-subnav/demo/color-context.html
  elements/rh-subnav/demo/color-context.js
  elements/rh-subnav/demo/demo.css
  elements/rh-subnav/demo/rh-subnav.html
  elements/rh-subnav/demo/rh-subnav.js
  elements/rh-subnav/docs/rh-subnav.md
  elements/rh-subnav/rh-subnav.css
  elements/rh-subnav/rh-subnav.ts
  elements/rh-subnav/test/rh-subnav.e2e.ts
  elements/rh-subnav/test/rh-subnav.spec.ts
  package-lock.json
Labels: in progress, for dev, high priority, Q1 2023

#436 feat(avatar): add rh-avatar
  .changeset/rh-avatar.md
  docs/_data/playgrounds.cjs
  elements/rh-avatar/README.md
  elements/rh-avatar/demo/color-context.html
  elements/rh-avatar/demo/color-context.js
  elements/rh-avatar/demo/demo.css
  elements/rh-avatar/demo/hopper.jpg
  elements/rh-avatar/demo/rh-avatar.html
  elements/rh-avatar/demo/rh-avatar.js
  elements/rh-avatar/demo/schoenfinkel.jpg
  elements/rh-avatar/docs/index.md
  elements/rh-avatar/random-pattern-controller.ts
  elements/rh-avatar/rh-avatar.css
  elements/rh-avatar/rh-avatar.ts
  elements/rh-avatar/test/rh-avatar.e2e.ts
  elements/rh-avatar/test/rh-avatar.spec.ts
  elements/rh-tabs/test/rh-tabs.spec.ts
Labels: Q1 2023

#758 fix(subnav): ensure link styles
  .changeset/modern-poets-check.md
  elements/rh-subnav/README.md
  elements/rh-subnav/rh-subnav.css
Labels: bug

#771 fix(subnav): add updateActiveItem for roving-tab-index controller
  .changeset/thin-paws-call.md
  elements/rh-subnav/demo/rh-subnav.html
  elements/rh-subnav/demo/rh-subnav.js
  elements/rh-subnav/rh-subnav.ts
Labels: bug

#781 fix(subnav): lightdom styles
  .changeset/giant-cobras-tease.md
  elements/rh-subnav/demo/color-context.html
  elements/rh-subnav/demo/rh-subnav.html
  elements/rh-subnav/rh-subnav-lightdom.css
Labels: enhancement

#779 docs: subnav lightdom css
  docs/_includes/layout-base.njk
  docs/elements.html
  docs/scss/styles.scss
Labels: documentation

#802 docs: subnav override of root font size
  docs/scss/_base/_base.scss
  docs/scss/styles.scss
Labels: bug

#814 fix(footer): accessible logo in universal
  .changeset/rh-footer-universal-svg-label.md
  elements/rh-footer/rh-footer-universal.ts
Labels: bug, a11y review

#835 fix(cta): use flex gap and remove inline padding
  .changeset/plenty-papayas-chew.md
  elements/rh-cta/rh-cta.css
Labels: bug

#836 fix(footer): a11y test failures
  elements/rh-footer/test/rh-footer.spec.ts
Labels: bug, a11y review

#852 docs(navigation-secondary): migrate to /elements
  docs/_data/migratedElements.cjs
  elements/rh-navigation-secondary/docs/00-overview.md
  elements/rh-navigation-secondary/docs/10-style.md
  elements/rh-navigation-secondary/docs/20-guidelines.md
  elements/rh-navigation-secondary/docs/30-behavior.md
  elements/rh-navigation-secondary/docs/40-code.md
  elements/rh-navigation-secondary/docs/50-accessibility.md
  elements/rh-navigation-secondary/docs/accessibility-tab-order.png
  elements/rh-navigation-secondary/docs/best-practice-1.png
  elements/rh-navigation-secondary/docs/best-practice-2.png
  elements/rh-navigation-secondary/docs/best-practice-3.png
  elements/rh-navigation-secondary/docs/best-practice-4.png
  elements/rh-navigation-secondary/docs/best-practice-5.png
  elements/rh-navigation-secondary/docs/breakpoints-large.png
  elements/rh-navigation-secondary/docs/breakpoints-small.png
  elements/rh-navigation-secondary/docs/collapsing-tray.png
  elements/rh-navigation-secondary/docs/current-page-indicator.png
  elements/rh-navigation-secondary/docs/expandable-tray-2-columns.png
  elements/rh-navigation-secondary/docs/expandable-tray-3-columns.png
  elements/rh-navigation-secondary/docs/expandable-tray-4-columns.png
  elements/rh-navigation-secondary/docs/expandable-tray-content-desktop.png
  elements/rh-navigation-secondary/docs/expandable-tray-content-mobile.png
  elements/rh-navigation-secondary/docs/expandable-tray-desktop.png
  elements/rh-navigation-secondary/docs/expandable-tray-mobile.png
  elements/rh-navigation-secondary/docs/interaction-state-active.png
  elements/rh-navigation-secondary/docs/interaction-state-default.png
  elements/rh-navigation-secondary/docs/interaction-state-focus.png
  elements/rh-navigation-secondary/docs/interaction-state-hover.png
  elements/rh-navigation-secondary/docs/layout-desktop.png
  elements/rh-navigation-secondary/docs/layout-mobile.png
  elements/rh-navigation-secondary/docs/left-to-right-languages.png
  elements/rh-navigation-secondary/docs/navigating-between-trays.png
  elements/rh-navigation-secondary/docs/navigation-content.png
  elements/rh-navigation-secondary/docs/navigation-slots.png
  elements/rh-navigation-secondary/docs/navigation-text-styles.png
  elements/rh-navigation-secondary/docs/product-name-text-stacking-1-lines.png
  elements/rh-navigation-secondary/docs/product-name-text-stacking-2-lines.png
  elements/rh-navigation-secondary/docs/product-name-text-stacking-3-lines.png
  elements/rh-navigation-secondary/docs/product-name-text-styling.png
  elements/rh-navigation-secondary/docs/right-to-left-languages.png
  elements/rh-navigation-secondary/docs/scrolling-with-primary-down.png
  elements/rh-navigation-secondary/docs/scrolling-with-primary-up.png
  elements/rh-navigation-secondary/docs/scrolling-with-tray-1.png
  elements/rh-navigation-secondary/docs/scrolling-with-tray-2.png
  elements/rh-navigation-secondary/docs/secondary-nav-example.png
  elements/rh-navigation-secondary/docs/secondary-nav-usage.png
  elements/rh-navigation-secondary/docs/spacing-extra-large.png
  elements/rh-navigation-secondary/docs/spacing-large.png
  elements/rh-navigation-secondary/docs/spacing-small.png
  elements/rh-navigation-secondary/docs/theme-option-dark.png
  elements/rh-navigation-secondary/docs/theme-option-light.png
  elements/rh-navigation-secondary/docs/zones-intro.png
  elements/rh-navigation-secondary/docs/zones-small-breakpoints.png
Labels: documentation

#815 fix(footer): resolves heading structure #795
  .changeset/rh-footer-sr-headers.md
  .changeset/rh-footer-universal-sr-logo.md
  elements/rh-footer/demo/footer-universal.html
  elements/rh-footer/rh-footer-universal.ts
  elements/rh-footer/rh-footer.css
  elements/rh-footer/rh-footer.ts
  elements/rh-footer/test/rh-footer.spec.ts
Labels: bug, a11y review

#866 fix(tabs): default context colors
  .changeset/tame-ducks-raise.md
  elements/rh-tabs/demo/rh-tabs.html
  elements/rh-tabs/demo/rh-tabs.js
  elements/rh-tabs/rh-tab.css
  elements/rh-tabs/rh-tabs.css
Labels: bug

#864 fix(navigation-secondary): correct colorPalette property
  .changeset/color-palette-light.md
  .changeset/rh-navigation-secondary-default-palette.md
  elements/rh-navigation-secondary/README.md
  elements/rh-navigation-secondary/rh-navigation-secondary-dropdown.ts
  elements/rh-navigation-secondary/rh-navigation-secondary.ts
  elements/rh-navigation-secondary/test/rh-navigation-secondary.spec.ts
  lib/context/color/provider.ts
Labels: bug

#878 fix(navigation-secondary): realign color-palette with surface tokens
  .changeset/eleven-hounds-cry.md
  elements/rh-navigation-secondary/rh-navigation-secondary.ts
  elements/rh-navigation-secondary/test/rh-navigation-secondary.spec.ts
Labels: bug
