Repository RedHat-UX/red-hat-design-system, pull requests merged in 2024-05, with the labels that each got.

#1573 chore(tabs): add a nested demo
  elements/rh-tabs/demo/nested.html
Labels: docs

#1574 fix(tag): font inheritance
  .changeset/tough-pens-brake.md
  elements/rh-tag/rh-tag.css
Labels: bug

#1575 fix(tabs): invert scroll functions when rtl, flip icons
  .changeset/curly-jobs-eat.md
  elements/rh-tabs/rh-tabs.css
  elements/rh-tabs/rh-tabs.ts
  elements/rh-tabs/test/rh-tabs.spec.ts
Labels: bug

#1498 docs(table): updated accessibility guidelines
  docs/accessibility/content.md
  elements/rh-table/docs/40-accessibility.md
Labels: for a11y review
