Repository RedHat-UX/red-hat-design-system, pull requests merged in 2024-04, with the labels that each got.

#1515 feat(skip-link): add `<rh-skip-link>`
  .changeset/slow-drinks-grow.md
  docs/_data/relatedItems.yaml
  docs/_data/repoStatus.yaml
  docs/patterns/skip-navigation/index.md
  elements/rh-skip-link/README.md
  elements/rh-skip-link/demo/rh-skip-link.html
  elements/rh-skip-link/docs/00-overview.md
  elements/rh-skip-link/docs/10-style.md
  elements/rh-skip-link/docs/20-guidelines.md
  elements/rh-skip-link/docs/30-code.md
  elements/rh-skip-link/docs/40-accessibility.md
  elements/rh-skip-link/docs/screenshot.png
  elements/rh-skip-link/docs/skip-link-anatomy.svg
  elements/rh-skip-link/docs/skip-link-focus-order.png
  elements/rh-skip-link/docs/skip-link-focus.svg
  elements/rh-skip-link/docs/skip-link-hover-and-active.svg
  elements/rh-skip-link/docs/skip-link-keyboard-navigation.png
  elements/rh-skip-link/docs/skip-link-placement.png
  elements/rh-skip-link/docs/skip-link-spacing.svg
  elements/rh-skip-link/docs/skip-link.svg
  elements/rh-skip-link/rh-skip-link-lightdom-shim.css
  elements/rh-skip-link/rh-skip-link.css
  elements/rh-skip-link/rh-skip-link.ts
  elements/rh-skip-link/test/rh-skip-link.e2e.ts
  elements/rh-skip-link/test/rh-skip-link.spec.ts
  package.json
Labels: feature

#1517 feat(back-to-top): add `<rh-back-to-top>`
  .changeset/late-cobras-hammer.md
  docs/_data/repoStatus.yaml
  docs/_plugins/shortcodes/repoStatus.cjs
  elements/rh-back-to-top/README.md
  elements/rh-back-to-top/demo/always-visible.html
  elements/rh-back-to-top/demo/color-context.html
  elements/rh-back-to-top/demo/no-slotted-text.html
  elements/rh-back-to-top/demo/position-sticky.html
  elements/rh-back-to-top/demo/rh-back-to-top.html
  elements/rh-back-to-top/demo/scroll-distance.html
  elements/rh-back-to-top/demo/warnings.html
  elements/rh-back-to-top/docs/10-overview.md
  elements/rh-back-to-top/docs/40-code.md
  elements/rh-back-to-top/docs/screenshot.png
  elements/rh-back-to-top/rh-back-to-top.css
  elements/rh-back-to-top/rh-back-to-top.ts
  elements/rh-back-to-top/test/rh-back-to-top.e2e.ts
  elements/rh-back-to-top/test/rh-back-to-top.spec.ts
Labels: feature

#1507 feat(site-status): add `<rh-site-status>`
  .changeset/hot-spiders-prove.md
  docs/_data/relatedItems.yaml
  docs/_data/repoStatus.yaml
  elements/rh-site-status/README.md
  elements/rh-site-status/demo/color-context.html
  elements/rh-site-status/demo/fetch-override.js
  elements/rh-site-status/demo/loading.html
  elements/rh-site-status/demo/rh-site-status.html
  elements/rh-site-status/demo/status-404.html
  elements/rh-site-status/demo/status-critical.html
  elements/rh-site-status/demo/status-maintenance.html
  elements/rh-site-status/demo/status-major.html
  elements/rh-site-status/demo/status-minor.html
  elements/rh-site-status/docs/00-overview.md
  elements/rh-site-status/docs/10-style.md
  elements/rh-site-status/docs/20-guidelines.md
  elements/rh-site-status/docs/30-code.md
  elements/rh-site-status/docs/40-accessibility.md
  elements/rh-site-status/docs/do.svg
  elements/rh-site-status/docs/dont.svg
  elements/rh-site-status/docs/screenshot.png
  elements/rh-site-status/docs/site-status-accessibility-footer.svg
  elements/rh-site-status/docs/site-status-anatomy.svg
  elements/rh-site-status/docs/site-status-configuration.svg
  elements/rh-site-status/docs/site-status-footer-mobile.svg
  elements/rh-site-status/docs/site-status-footer-placement.svg
  elements/rh-site-status/docs/site-status-footer.svg
  elements/rh-site-status/docs/site-status-icons-do.svg
  elements/rh-site-status/docs/site-status-icons-dont-long-text.svg
  elements/rh-site-status/docs/site-status-icons-dont-no-icon.svg
  elements/rh-site-status/docs/site-status-icons-dont.svg
  elements/rh-site-status/docs/site-status-icons.svg
  elements/rh-site-status/docs/site-status-interaction-states.svg
  elements/rh-site-status/docs/site-status-sample.svg
  elements/rh-site-status/docs/site-status-space.svg
  elements/rh-site-status/docs/site-status-theme.svg
  elements/rh-site-status/rh-site-status.css
  elements/rh-site-status/rh-site-status.ts
  elements/rh-site-status/test/rh-site-status.e2e.ts
  elements/rh-site-status/test/rh-site-status.spec.ts
Labels: feature

#1439 docs: add Get started: Developers
  docs/_includes/component/header.njk
  docs/_includes/layout-with-subnav.njk
  docs/_plugins/rhds.cjs
  docs/foundations/color/accessibility.md
  docs/foundations/color/index.md
  docs/foundations/color/usage.md
  docs/get-started.md
  docs/get-started/designers.md
  docs/get-started/developers/index.md
  docs/get-started/developers/installation.md
  docs/get-started/developers/tokens.md
  docs/get-started/developers/usage.md
Labels: docs

#1529 fix(menu): improve keyboard accessibility on firefox
  .changeset/large-kings-drop.md
  elements/rh-button/rh-button.ts
  elements/rh-menu/demo/color-context.html
  elements/rh-menu/demo/position-left.html
  elements/rh-menu/demo/position-right.html
  elements/rh-menu/demo/position-top.html
  elements/rh-menu/demo/rh-menu.html
  elements/rh-menu/rh-menu.css
  elements/rh-menu/rh-menu.ts
Labels: bug
