Repository RedHat-UX/red-hat-design-system, pull requests merged in 2024-01, with the labels that each got.

#1373 feat(table): color context support
  .changeset/calm-fishes-sleep.md
  elements/rh-table/demo/color-context.html
  elements/rh-table/rh-sort-button.css
  elements/rh-table/rh-sort-button.ts
  elements/rh-table/rh-table-lightdom.css
  elements/rh-table/rh-table.css
  elements/rh-table/rh-table.ts
Labels: feature

#1318 feat(surface): add `<rh-surface>` element
  .changeset/dry-houses-wash.md
  docs/patterns/card/index.md
  elements/rh-audio-player/rh-audio-player.ts
  elements/rh-context-provider/rh-context-provider.ts
  elements/rh-cta/rh-cta.ts
  elements/rh-dialog/rh-dialog.ts
  elements/rh-navigation-secondary/rh-navigation-secondary.css
  elements/rh-navigation-secondary/rh-navigation-secondary.ts
  elements/rh-surface/README.md
  elements/rh-surface/demo/rh-surface.html
  elements/rh-surface/docs/00-overview.md
  elements/rh-surface/docs/10-style.md
  elements/rh-surface/docs/20-guidelines.md
  elements/rh-surface/docs/30-code.md
  elements/rh-surface/docs/screenshot.png
  elements/rh-surface/rh-surface.css
  elements/rh-surface/rh-surface.ts
  elements/rh-surface/test/rh-surface.e2e.ts
  elements/rh-surface/test/rh-surface.spec.ts
  elements/rh-tile/demo/tile-group-disabled.html
  elements/rh-tile/demo/tile-group-radio-disabled.html
  elements/rh-tile/demo/tile-group-radio.html
  lib/elements/rh-context-demo/rh-context-demo.ts
  lib/elements/rh-context-picker/rh-context-picker.ts
  lib/elements/rh-context-provider/README.md
  lib/elements/rh-context-provider/demo/demo.css
  lib/elements/rh-context-provider/demo/nested-contexts.html
  lib/elements/rh-context-provider/demo/rh-context-provider.html
  lib/elements/rh-context-provider/rh-context-provider.ts
Labels: feature

#1409 fix(table): improve styles for color context
  .changeset/rotten-oranges-count.md
  elements/rh-table/rh-table-lightdom.css
  elements/rh-table/rh-table.css
  elements/rh-table/rh-table.ts
Labels: bug

#1415 fix(table): mobile th:before styles
  elements/rh-table/demo/row-and-column-headers.html
  elements/rh-table/rh-table-lightdom.css
Labels: bug

#1419 Updating v1.3 release notes
  docs/release-notes.md
Labels: docs
