Repository RedHat-UX/red-hat-design-system, pull requests merged in 2025-07, with the labels that each got.

#2331 fix(tabs): correct vertical tabs layout and background styles
  .changeset/curvy-animals-invite.md
  .changeset/eager-tables-rest.md
  .changeset/shiny-boxes-tease.md
  elements/rh-tabs/rh-tab-panel.css
  elements/rh-tabs/rh-tab.css
  elements/rh-tabs/rh-tabs.css
  elements/rh-tabs/rh-tabs.ts
Labels: bug

#2463 feat(navigation-primary): bimodal logo
  .changeset/fruity-snakes-push.md
  elements/rh-navigation-primary/rh-navigation-primary.css
  elements/rh-navigation-primary/rh-navigation-primary.ts
Labels: feature

#2462 fix(navigation-primary): hamburger standalones toggle state
  .changeset/heavy-hornets-throw.md
  elements/rh-navigation-primary/rh-navigation-primary-item.ts
  elements/rh-navigation-primary/rh-navigation-primary.ts
  elements/rh-navigation-primary/test/rh-navigation-primary.spec.ts
Labels: bug

#2461 docs(video-embed): fixing demo thumbnails
  elements/rh-video-embed/demo/alignment.html
  elements/rh-video-embed/demo/card-with-video.html
  elements/rh-video-embed/demo/color-context.html
  elements/rh-video-embed/demo/no-caption.html
  elements/rh-video-embed/demo/require-consent.html
  elements/rh-video-embed/demo/rh-video-embed.html
  elements/rh-video-embed/demo/video-thumb.jpg
Labels: bug, docs
