Repository RedHat-UX/red-hat-design-system, pull requests merged in 2025-03, with the labels that each got.

#2189 docs: update accessibility > design imagery
  docs/accessibility/design.md
Labels: bug, docs

#2224 docs(footer): add default slot description for `<rh-footer-social-link>`
  elements/rh-footer/rh-footer-social-link.ts
Labels: docs

#1995 fix(health-index): prevent graphical elements breaking out of stacking context
  .changeset/eighty-windows-exist.md
  elements/rh-health-index/rh-health-index.css
Labels: bug

#2210 docs(hp): improving mobile styles
  docs/assets/home/hero-image.png
  docs/assets/home/hero-image.svg
  docs/index.html
  docs/styles/grid.css
Labels: docs

#2212 fix(subnav): overflow scrolling
  .changeset/nasty-apes-push.md
  elements/rh-subnav/demo/right-to-left.html
  elements/rh-subnav/rh-subnav.css
  elements/rh-subnav/rh-subnav.ts
  elements/rh-subnav/test/rh-subnav.spec.ts
Labels: bug

#2243 docs(pagination): remove `rh-surface` from pagination demos
  elements/rh-pagination/demo/compact.html
  elements/rh-pagination/demo/many-pages.html
  elements/rh-pagination/demo/no-numeric-control.html
  elements/rh-pagination/demo/open-compact-size.html
  elements/rh-pagination/demo/open-compact.html
  elements/rh-pagination/demo/open.html
  elements/rh-pagination/demo/overflow.html
  elements/rh-pagination/demo/rh-pagination.html
  elements/rh-pagination/demo/right-to-left.html
  elements/rh-pagination/demo/size-compact.html
  elements/rh-pagination/demo/size.html
  elements/rh-pagination/docs/30-code.md
Labels: docs

#2249 fix(navigation-secondary): panel scrollbar visible only when overflowed
  .changeset/proud-hands-sit.md
  elements/rh-navigation-secondary/rh-navigation-secondary-menu.css
Labels: bug
